export default Data =[
    {id: 1,text:"A", color:"red"},
    {id: 2,text:"B", color:"blue"},
    {id: 3,text:"C", color:"yellow"},
    {id: 4,text:"D", color:"green"},
    {id: 5,text:"E", color:"orange"},
    {id: 6,text:"F", color:"orange"},
    {id: 7,text:"G", color:"orange"},
    {id: 8,text:"H", color:"orange"},
    {id: 9,text:"I", color:"orange"},
    {id: 10,text:"J", color:"orange"},
    {id: 11,text:"K", color:"orange"},
    {id: 12,text:"L", color:"orange"},
    {id: 13,text:"M", color:"orange"},
    {id: 14,text:"N", color:"orange"},
    {id: 15,text:"O", color:"orange"},
    {id: 16,text:"P", color:"orange"},
    {id: 17,text:"Q", color:"orange"},
    {id: 18,text:"R", color:"orange"},
    {id: 19,text:"S", color:"orange"},
    {id: 20,text:"T", color:"orange"},
    {id: 21,text:"U", color:"orange"},
    {id: 22,text:"V", color:"orange"},
    {id: 23,text:"W", color:"orange"},
    {id: 24,text:"X", color:"orange"},
    {id: 25,text:"Y", color:"orange"},
    {id: 26,text:"Z", color:"orange"},


]